-- Take the anon grant off bank_sync_log_facets().
--
-- The function was created with `revoke all ... from public` plus a grant to authenticated, which
-- reads as "signed-in callers only" and is not what happened: this project ships
-- `alter default privileges in schema public grant all on functions to anon, ...`, so a DIRECT
-- grant to anon lands on every new function and a revoke from PUBLIC does not touch it.
--
-- Nothing leaked. The function is security invoker, so an anonymous caller runs it under the anon
-- role and bank_sync_logs' SELECT policy returns nothing: probing it live gives back empty arrays.
-- Revoked anyway, because a function that answers an unauthenticated caller at all is one policy
-- change away from answering with data, and the grant not matching the stated intent is how that
-- change goes unnoticed.
revoke execute on function public.bank_sync_log_facets() from anon;
