-- Same change as immonetz's 20260909140000: the review columns now run the badge's own
-- re-check (belegNachgeprueft) inside the database, via functions GENERATED from the shared rule
-- declarations (src/features/invoice-detail/recheck-rules.ts). Verified per row against the
-- TypeScript output on live data: 499 rows, 0 mismatches.

begin;

-- GENERATED by scripts/generate-review-recheck-sql.ts from
-- src/features/invoice-detail/recheck-rules.ts and pruefung.ts. Do not edit by hand:
-- change the rules and regenerate, so the badge and this function cannot drift apart.

create or replace function public.invoice_iban_checksum_ok(candidate text)
returns boolean
language sql
immutable
set search_path to 'public'
as $fn$
  with cleaned as (
    select upper(regexp_replace(btrim(coalesce(candidate, '')), '\s', '', 'g')) as s
  ),
  rearranged as (
    select substr(s, 5) || substr(s, 1, 4) as r, s from cleaned
  ),
  expanded as (
    select string_agg(
      case when ch ~ '[0-9]' then ch else (ascii(ch) - 55)::text end, '' order by ord
    ) as digits
    from rearranged, regexp_split_to_table(r, '') with ordinality as t(ch, ord)
  )
  select case
    when (select s from cleaned) !~ '^[A-Z0-9]{15,34}$' then false
    when (select s from cleaned) !~ '^[A-Z]{2}[0-9]{2}' then false
    else (select digits from expanded)::numeric % 97 = 1
  end;
$fn$;

create or replace function public.invoice_review_state(
  p_validation_detail jsonb,
  p_extracted jsonb,
  p_validation jsonb,
  p_issuer text,
  p_invoice_number text,
  p_document_date date,
  p_amount_gross numeric,
  p_amount_net numeric,
  p_vat_amount numeric,
  p_vat_rate numeric,
  p_recipient_name text,
  p_company_code text,
  p_supplier_iban text
)
returns table(problem_count integer, unchecked boolean)
language sql
stable
set search_path to 'public'
as $fn$
  with raw_detail as (
    select coalesce(
      case when jsonb_typeof(p_validation_detail) = 'object' and p_validation_detail <> '{}'::jsonb
        then p_validation_detail end,
      case when jsonb_typeof(p_extracted -> 'validation_detail') = 'object'
            and (p_extracted -> 'validation_detail') <> '{}'::jsonb
        then p_extracted -> 'validation_detail' end,
      '{}'::jsonb
    ) as d
  ),
  halves as (
    select
      case
        when d ? 'bookkeeping_edits' then
          case when jsonb_typeof(d -> 'bookkeeping_edits') = 'object'
                and (d -> 'bookkeeping_edits') <> '{}'::jsonb
            then d -> 'bookkeeping_edits' else '{}'::jsonb end
        else d
      end as basis,
      case
        when d ? 'bookkeeping_edits' and jsonb_typeof(d -> 'user_edits') = 'object'
          then coalesce(d -> 'user_edits', '{}'::jsonb)
        else '{}'::jsonb
      end as stored_user
    from raw_detail
  ),
  iban_input as (
    select coalesce(
      nullif(btrim(coalesce(p_supplier_iban, '')), ''),
      case when jsonb_typeof(p_extracted -> 'iban') = 'string' then p_extracted ->> 'iban' end
    ) as src
  ),
  iban_candidates as (
    select coalesce(array_agg(part) filter (where part <> ''), '{}'::text[]) as arr
    from iban_input,
      lateral (
        select btrim(piece) as part
        from regexp_split_to_table(coalesce(src, ''), '(?i)([;,/|]|\s{2,}|\y(?:und)\y)') as piece
      ) parts
    where src is not null
  ),
  numbers as (
    select
      coalesce(
        case
          when jsonb_typeof(p_extracted -> 'zwischensumme_brutto') = 'number'
            then (p_extracted ->> 'zwischensumme_brutto')::numeric
          when jsonb_typeof(p_extracted -> 'zwischensumme_brutto') = 'string'
                and (p_extracted ->> 'zwischensumme_brutto') ~ '^\s*[+-]?([0-9]+\.?[0-9]*|\.[0-9]+)([eE][+-]?[0-9]+)?\s*$'
            then btrim(p_extracted ->> 'zwischensumme_brutto')::numeric
        end,
        p_amount_gross
      ) as subtotal
  ),
  active_rates as (
    select array_agg(rate) as rates
    from halves,
      lateral (
        select case
          when jsonb_typeof(elem) = 'number' then (elem #>> '{}')::numeric
          when jsonb_typeof(elem) = 'string' and (elem #>> '{}') ~ '^\s*[+-]?([0-9]+\.?[0-9]*|\.[0-9]+)([eE][+-]?[0-9]+)?\s*$'
            then btrim(elem #>> '{}')::numeric
        end as rate
        from jsonb_array_elements(
          case when jsonb_typeof(basis -> 'vat_rate_valid' -> 'values' -> 'active_rates') = 'array'
            then basis -> 'vat_rate_valid' -> 'values' -> 'active_rates'
            else '[]'::jsonb end
        ) as elem
      ) parsed
    where parsed.rate is not null
  ),
  recheck as (
    select jsonb_build_object(
      'iban_checksum_valid', case when cardinality(iban_candidates.arr) = 0 then 'not_applicable'
          when (select bool_and(public.invoice_iban_checksum_ok(c)) from unnest(iban_candidates.arr) c)
            then 'ok' else 'failed' end,
      'payable_iban_present', case when lower(btrim(coalesce(halves.basis -> 'payable_iban_present' ->> 'status', ''))) = 'not_applicable'
          then 'not_applicable'
          else case when cardinality(iban_candidates.arr) > 0 then 'ok' else 'failed' end end,
      'iban_unambiguous', case when lower(btrim(coalesce(halves.basis -> 'iban_unambiguous' ->> 'status', ''))) = 'not_applicable'
          then 'not_applicable'
          else case when cardinality(iban_candidates.arr) = 0 then 'not_applicable'
          when cardinality(iban_candidates.arr) <= 1 then 'ok' else 'failed' end end,
      'gross_present', case when p_amount_gross is not null then 'ok' else 'failed' end,
      'issuer_present', case when btrim(coalesce(p_issuer, '')) <> '' then 'ok' else 'failed' end,
      'date_present', case when p_document_date is not null then 'ok' else 'failed' end,
      'invoice_number_present', case when btrim(coalesce(p_invoice_number, '')) <> '' then 'ok' else 'failed' end,
      'sum_matches', case when numbers.subtotal is null or p_amount_net is null or p_vat_amount is null
          then 'not_applicable'
          when abs((p_amount_net::float8 + p_vat_amount::float8) - numbers.subtotal::float8) <= 0.02 then 'ok'
          else 'failed' end,
      'vat_rate_valid', case when p_vat_rate is null or active_rates.rates is null then 'not_applicable'
          when floor(p_vat_rate + 0.5) = any(active_rates.rates) then 'ok' else 'failed' end,
      'date_not_future', case when p_document_date is null then 'not_applicable'
          when p_document_date <= current_date then 'ok' else 'failed' end,
      'recipient_present', case when lower(btrim(coalesce(halves.basis -> 'recipient_present' ->> 'status', ''))) = 'not_applicable'
          then 'not_applicable'
          else case when btrim(coalesce(p_recipient_name, '')) <> '' then 'ok' else 'failed' end end,
      'assignment_resolved', case when btrim(coalesce(p_company_code, '')) <> '' then 'ok' else 'failed' end
    ) as m
    from halves, iban_candidates, numbers, active_rates
  ),
  final_detail as (
    select case
      when halves.basis <> '{}'::jsonb then coalesce(
        (
          select jsonb_object_agg(
            entry.check_key,
            case when recheck.m ? entry.check_key and jsonb_typeof(entry.check_value) = 'object'
              then jsonb_set(entry.check_value, '{status}', recheck.m -> entry.check_key)
              else entry.check_value end
          )
          from jsonb_each(halves.basis) as entry(check_key, check_value)
        ), '{}'::jsonb)
      else halves.stored_user
    end as detail
    from halves, recheck
  ),
  checks_tier as (
    select case
      when jsonb_typeof(p_extracted -> 'review_checks') = 'array'
            and jsonb_array_length(p_extracted -> 'review_checks') > 0
        then p_extracted -> 'review_checks' end as arr
  ),
  flat_tier as (
    select coalesce(
      case when jsonb_typeof(p_extracted -> 'validation') = 'object'
        then p_extracted -> 'validation' end,
      p_validation, '{}'::jsonb) as fv
  )
  select
    (case
      when final_detail.detail <> '{}'::jsonb then (
        select count(*)::int from jsonb_each(final_detail.detail) as entry(check_key, check_value)
        where entry.check_key in ('gross_present','issuer_present','sum_matches','vat_rate_valid','iban_checksum_valid','date_not_future','invoice_number_present','date_present','payable_iban_present','recipient_present','iban_unambiguous','relevance_ok','assignment_resolved','brutto_vorhanden','steller_vorhanden','summe_ok','ust_satz_ok','iban_ok','datum_plausibel','rechnungsnr_vorhanden','datum_vorhanden','iban_vorhanden','empfaenger_vorhanden')
          and btrim(lower(coalesce(entry.check_value ->> 'status', ''))) not in ('', 'ok', 'not_applicable', 'skipped')
      )
      when checks_tier.arr is not null then (
        select count(*)::int from jsonb_array_elements(checks_tier.arr) as review_check(value)
        where btrim(lower(coalesce(review_check.value ->> 'severity', ''))) <> 'informational'
          and coalesce(review_check.value ->> 'field', '') in ('iban_anzahl','extraction_confidence','relevance','document_readable','exclusion','brutto_vorhanden','steller_vorhanden','summe_ok','ust_satz_ok','iban_ok','datum_plausibel','rechnungsnr_vorhanden','datum_vorhanden','empfaenger_name','assignment','safety_invariant_1','safety_invariant_2','safety_invariant_3','safety_invariant_4a','safety_invariant_4b','safety_invariant_5','forced_review')
          and btrim(lower(coalesce(review_check.value ->> 'status', ''))) not in ('', 'ok', 'not_applicable', 'skipped')
      )
      else (
        select count(*)::int from jsonb_each_text(flat_tier.fv) as gate(gate_name, gate_value)
        where gate.gate_name in ('brutto_vorhanden','steller_vorhanden','datum_vorhanden','rechnungsnr_vorhanden','summe_ok','ust_satz_ok','iban_ok','datum_plausibel')
          and gate.gate_value = 'false'
          and (gate.gate_name not in ('rechnungsnr_vorhanden','datum_vorhanden')
               or coalesce(flat_tier.fv ->> 'kleinbetrag', '') <> 'true')
      )
    end) as problem_count,
    (case
      when final_detail.detail <> '{}'::jsonb then
        not exists (
          select 1 from jsonb_each(final_detail.detail) as entry(check_key, check_value)
          where entry.check_key not in ('kleinbetrag','is_small_amount')
            and btrim(lower(coalesce(entry.check_value ->> 'status', ''))) not in ('', 'not_applicable', 'skipped')
        )
      when checks_tier.arr is not null then
        not exists (
          select 1 from jsonb_array_elements(checks_tier.arr) as review_check(value)
          where btrim(lower(coalesce(review_check.value ->> 'severity', ''))) <> 'informational'
            and btrim(lower(coalesce(review_check.value ->> 'status', ''))) not in ('', 'not_applicable', 'skipped')
        )
      else
        not exists (
          select 1 from jsonb_each_text(flat_tier.fv) as gate(gate_name, gate_value)
          where gate.gate_name in ('brutto_vorhanden','steller_vorhanden','datum_vorhanden','rechnungsnr_vorhanden','summe_ok','ust_satz_ok','iban_ok','datum_plausibel')
            and (gate.gate_value = 'true'
                 or (gate.gate_value = 'false'
                     and (gate.gate_name not in ('rechnungsnr_vorhanden','datum_vorhanden')
                          or coalesce(flat_tier.fv ->> 'kleinbetrag', '') <> 'true')))
        )
    end) as unchecked
  from final_detail, checks_tier, flat_tier;
$fn$;

revoke execute on function public.invoice_iban_checksum_ok(text) from public, anon;
grant execute on function public.invoice_iban_checksum_ok(text) to authenticated, service_role;
revoke execute on function public.invoice_review_state(jsonb, jsonb, jsonb, text, text, date, numeric, numeric, numeric, numeric, text, text, text) from public, anon;
grant execute on function public.invoice_review_state(jsonb, jsonb, jsonb, text, text, date, numeric, numeric, numeric, numeric, text, text, text) to authenticated, service_role;

create or replace view public.v_invoices_review with (security_invoker = true) as
select sub.*,
  (rs.problem_count)::integer as review_problem_count,
  rs.unchecked as review_unchecked,
  lower(
      coalesce(sub.issuer, '') || ' ' ||
      coalesce(sub.invoice_number, '') || ' ' ||
      coalesce(sub.service_description, '') || ' ' ||
      coalesce(sub.cost_category, '') || ' ' ||
      coalesce(to_char(sub.amount_gross, 'FM9999999990.00'), '') || ' ' ||
      coalesce(replace(to_char(sub.amount_gross, 'FM9999999990.00'), '.', ','), '') || ' ' ||
      coalesce(to_char(sub.amount_gross, 'FM9,999,999,990.00'), '') || ' ' ||
      coalesce(replace(replace(replace(to_char(sub.amount_gross, 'FM9,999,999,990.00'),
        ',', '#'), '.', ','), '#', '.'), '')
    ) as search_text
from (SELECT sub_1_1.id,
                    sub_1_1.company_id,
                    sub_1_1.company_code,
                    sub_1_1.supplier_id,
                    sub_1_1.issuer,
                    sub_1_1.document_type,
                    sub_1_1.document_date,
                    sub_1_1.service_date,
                    sub_1_1.invoice_number,
                    sub_1_1.amount_net,
                    sub_1_1.vat_rate,
                    sub_1_1.vat_amount,
                    sub_1_1.amount_gross,
                    sub_1_1.currency,
                    sub_1_1.is_small_amount,
                    sub_1_1.intake_channel,
                    sub_1_1.source,
                    sub_1_1.property_code,
                    sub_1_1.storage_path,
                    sub_1_1.ocr_fulltext,
                    sub_1_1.status,
                    sub_1_1.extracted,
                    sub_1_1.validation,
                    sub_1_1.gmail_message_id,
                    sub_1_1.created_at,
                    sub_1_1.service_period_from,
                    sub_1_1.service_period_to,
                    sub_1_1.cost_category,
                    sub_1_1.service_description,
                    sub_1_1.line_items,
                    sub_1_1.tax,
                    sub_1_1.issuer_address,
                    sub_1_1.recipient_name,
                    sub_1_1.recipient_address,
                    sub_1_1.customer_number,
                    sub_1_1.payment_reference,
                    sub_1_1.payment_method,
                    sub_1_1.tax_note,
                    sub_1_1.traffic_light,
                    sub_1_1.confidence_score,
                    sub_1_1.already_paid,
                    sub_1_1.fts,
                    sub_1_1.embedding,
                    sub_1_1.property_id,
                    sub_1_1.source_document_id,
                    sub_1_1.page_range,
                    sub_1_1.vat_treatment,
                    sub_1_1.business_line_id,
                    sub_1_1.business_line_code,
                    sub_1_1.assignment_source,
                    sub_1_1.workflow_status,
                    sub_1_1.assigned_to,
                    sub_1_1.order_number,
                    sub_1_1.due_date,
                    sub_1_1.paid_at,
                    sub_1_1.updated_at,
                    sub_1_1.deleted_at,
                    sub_1_1.deleted_by,
                    sub_1_1.delete_reason,
                    sub_1_1.paid_source,
                    sub_1_1.vat_source,
                    sub_1_1.cost_category_source,
                    sub_1_1.not_relevant_at,
                    sub_1_1.not_relevant_by,
                    sub_1_1.not_relevant_note,
                    sub_1_1.mailbox_reset_at,
                    sub_1_1.archived_at,
                    sub_1_1.archived_by,
                    sub_1_1.archive_note,
                    sub_1_1.assignment_decided_by,
                    sub_1_1.category_id,
                    sub_1_1.vat_deductible_pct,
                    sub_1_1.vat_deductibility_source,
                    sub_1_1.vat_special_case,
                    sub_1_1.vat_conflict_at,
                    sub_1_1.vat_conflict_note,
                    sub_1_1.vat_deductible_amount,
                    sub_1_1.vat_nondeductible_amount,
                    sub_1_1.datev_handed_over_at,
                    sub_1_1.datev_batch_id,
                    sub_1_1.issuer_sort,
                    sub_1_1.review_score,
                    sub_1_1.has_suggested_bank_match,
                    sub_1_1.has_confirmed_bank_match,
                    i.company_assignment_source,
                    i.property_assignment_source
                   FROM (( SELECT v_invoices_list.id,
                            v_invoices_list.company_id,
                            v_invoices_list.company_code,
                            v_invoices_list.supplier_id,
                            v_invoices_list.issuer,
                            v_invoices_list.document_type,
                            v_invoices_list.document_date,
                            v_invoices_list.service_date,
                            v_invoices_list.invoice_number,
                            v_invoices_list.amount_net,
                            v_invoices_list.vat_rate,
                            v_invoices_list.vat_amount,
                            v_invoices_list.amount_gross,
                            v_invoices_list.currency,
                            v_invoices_list.is_small_amount,
                            v_invoices_list.intake_channel,
                            v_invoices_list.source,
                            v_invoices_list.property_code,
                            v_invoices_list.storage_path,
                            v_invoices_list.ocr_fulltext,
                            v_invoices_list.status,
                            v_invoices_list.extracted,
                            v_invoices_list.validation,
                            v_invoices_list.gmail_message_id,
                            v_invoices_list.created_at,
                            v_invoices_list.service_period_from,
                            v_invoices_list.service_period_to,
                            v_invoices_list.cost_category,
                            v_invoices_list.service_description,
                            v_invoices_list.line_items,
                            v_invoices_list.tax,
                            v_invoices_list.issuer_address,
                            v_invoices_list.recipient_name,
                            v_invoices_list.recipient_address,
                            v_invoices_list.customer_number,
                            v_invoices_list.payment_reference,
                            v_invoices_list.payment_method,
                            v_invoices_list.tax_note,
                            v_invoices_list.traffic_light,
                            v_invoices_list.confidence_score,
                            v_invoices_list.already_paid,
                            v_invoices_list.fts,
                            v_invoices_list.embedding,
                            v_invoices_list.property_id,
                            v_invoices_list.source_document_id,
                            v_invoices_list.page_range,
                            v_invoices_list.vat_treatment,
                            v_invoices_list.business_line_id,
                            v_invoices_list.business_line_code,
                            v_invoices_list.assignment_source,
                            v_invoices_list.workflow_status,
                            v_invoices_list.assigned_to,
                            v_invoices_list.order_number,
                            v_invoices_list.due_date,
                            v_invoices_list.paid_at,
                            v_invoices_list.updated_at,
                            v_invoices_list.deleted_at,
                            v_invoices_list.deleted_by,
                            v_invoices_list.delete_reason,
                            v_invoices_list.paid_source,
                            v_invoices_list.vat_source,
                            v_invoices_list.cost_category_source,
                            v_invoices_list.not_relevant_at,
                            v_invoices_list.not_relevant_by,
                            v_invoices_list.not_relevant_note,
                            v_invoices_list.mailbox_reset_at,
                            v_invoices_list.archived_at,
                            v_invoices_list.archived_by,
                            v_invoices_list.archive_note,
                            v_invoices_list.assignment_decided_by,
                            v_invoices_list.category_id,
                            v_invoices_list.vat_deductible_pct,
                            v_invoices_list.vat_deductibility_source,
                            v_invoices_list.vat_special_case,
                            v_invoices_list.vat_conflict_at,
                            v_invoices_list.vat_conflict_note,
                            v_invoices_list.vat_deductible_amount,
                            v_invoices_list.vat_nondeductible_amount,
                            v_invoices_list.datev_handed_over_at,
                            v_invoices_list.datev_batch_id,
                            v_invoices_list.issuer_sort,
                            v_invoices_list.review_score,
                            v_invoices_list.has_suggested_bank_match,
                            v_invoices_list.has_confirmed_bank_match
                           FROM v_invoices_list) sub_1_1
                     LEFT JOIN invoices i ON ((i.id = sub_1_1.id)))) sub
left join public.invoices bi on bi.id = sub.id
left join public.suppliers sup on sup.id = sub.supplier_id
cross join lateral public.invoice_review_state(
  bi.validation_detail, sub.extracted, bi.validation, sub.issuer, sub.invoice_number,
  sub.document_date, sub.amount_gross, sub.amount_net, sub.vat_amount, sub.vat_rate,
  sub.recipient_name, sub.company_code, sup.iban
) rs;

commit;
