import type { BankTransaction } from "@/lib/data/types";
import { COMPANIES, SUPPLIERS, sampleId } from "../shared";

const base = {
  connection_id: sampleId(71, 1),
  currency: "EUR",
  counterparty_bic: null,
  spender_name: null,
  spender_email: null,
  transaction_type: null,
  transaction_type_source: "auto" as const,
  fully_used_at: null,
  fully_used_by: null,
  fully_used_note: null,
  pleo_tag_id: null,
  pleo_account_id: null,
  is_sandbox: false,
  raw_data: null,
  imported_at: "2026-09-21T05:00:00Z",
  created_at: "2026-09-21T05:00:00Z",
  no_receipt_reason: null,
  whitelist_rule_id: null,
  no_receipt_set_by: null,
  no_receipt_set_at: null,
  category_id: null,
  category_source: null,
  source: "banksapi",
};

/**
 * The four states the transactions screen draws differently: matched to a document, a suggestion
 * waiting to be confirmed, nothing found yet, and money in rather than out. Anything else is the
 * same row again with different numbers.
 */
export const bankTransactions: BankTransaction[] = [
  {
    ...base,
    id: sampleId(80, 1),
    account_id: sampleId(70, 1),
    company_id: COMPANIES[0].id,
    provider_hash: "seed-80-1",
    amount: -1499.4,
    booking_date: "2026-09-05",
    value_date: "2026-09-05",
    payment_reference: "Rechnung 2026-1180",
    booking_text: "Überweisung",
    counterparty_holder: SUPPLIERS[2].name,
    counterparty_iban: "DE89370400440532013000",
    direction: "ausgehend",
    matching_status: "matched",
    has_suggested_match: false,
    has_document: true,
    document_source: "pipeline",
  } as BankTransaction,
  {
    ...base,
    id: sampleId(80, 2),
    account_id: sampleId(70, 1),
    company_id: COMPANIES[0].id,
    provider_hash: "seed-80-2",
    amount: -250,
    booking_date: "2026-09-16",
    value_date: "2026-09-16",
    payment_reference: "RE-2026-0914 Abschlag",
    booking_text: "Lastschrift",
    counterparty_holder: SUPPLIERS[0].name,
    counterparty_iban: "DE02120300000000202051",
    direction: "ausgehend",
    matching_status: "suggestion",
    has_suggested_match: true,
    has_document: false,
    document_source: null,
  } as BankTransaction,
  {
    ...base,
    id: sampleId(80, 3),
    account_id: sampleId(70, 2),
    company_id: COMPANIES[1].id,
    provider_hash: "seed-80-3",
    amount: -64.9,
    booking_date: "2026-09-18",
    value_date: "2026-09-18",
    payment_reference: "Kartenzahlung Baumarkt",
    booking_text: "Kartenzahlung",
    counterparty_holder: "Baumarkt Nord",
    counterparty_iban: null,
    direction: "ausgehend",
    matching_status: "open",
    has_suggested_match: false,
    has_document: false,
    document_source: null,
  } as BankTransaction,
  {
    ...base,
    id: sampleId(80, 4),
    account_id: sampleId(70, 2),
    company_id: COMPANIES[1].id,
    provider_hash: "seed-80-4",
    amount: 1450,
    booking_date: "2026-09-01",
    value_date: "2026-09-01",
    payment_reference: "Miete September Hafenstraße 12",
    booking_text: "Gutschrift",
    counterparty_holder: "Jonas Wieland",
    counterparty_iban: null,
    direction: "eingehend",
    matching_status: "open",
    has_suggested_match: false,
    has_document: false,
    document_source: null,
  } as BankTransaction,
];
