import type { Customer } from "@/lib/data/types";
import { COMPANIES, sampleId } from "../shared";

/** A company customer and a private one: the two the outgoing-invoice screens address differently. */
export const customers: Customer[] = [
  {
    id: sampleId(50, 1),
    company_id: COMPANIES[0].id,
    is_company: true,
    name: "Baumann & Partner mbB",
    contact_person: "Frau Baumann",
    email: "rechnung@baumann-partner.example",
    phone: null,
    address_street: "Königstraße 8",
    address_zip: "24103",
    address_city: "Kiel",
    address_country_code: "DE",
    vat_id: "DE298764511",
    customer_number: "K-1001",
    normalized_name: "baumann partner mbb",
    source: "app",
    created_at: "2026-02-02T10:00:00Z",
    updated_at: "2026-02-02T10:00:00Z",
    deleted_at: null,
    deleted_by: null,
    delete_reason: null,
  },
  {
    id: sampleId(50, 2),
    company_id: COMPANIES[1].id,
    is_company: false,
    name: "Jonas Wieland",
    contact_person: null,
    email: null,
    phone: null,
    address_street: "Hafenstraße 12",
    address_zip: "24103",
    address_city: "Kiel",
    address_country_code: "DE",
    vat_id: null,
    customer_number: "K-1002",
    normalized_name: "jonas wieland",
    source: "app",
    created_at: "2026-03-11T13:20:00Z",
    updated_at: "2026-03-11T13:20:00Z",
    deleted_at: null,
    deleted_by: null,
    delete_reason: null,
  },
];
