// Renders the review re-check rules (src/features/invoice-detail/recheck-rules.ts) into the SQL
// function the v_invoices_review columns use, so the database filter and the rendered badge run
// the SAME rules. Never edit the generated SQL by hand — change the rules and re-run:
//
//   npx tsx scripts/generate-review-recheck-sql.ts supabase/migrations/<version>_<name>.sql
//
// The wrapper migration that plugs the function into the view is hub-specific and stays
// hand-written; only invoice_review_state()/invoice_iban_checksum_ok() are generated.
import { writeFileSync } from "node:fs";

import {
  IBAN_JOINING_WORDS,
  IBAN_SEPARATOR_PATTERN,
  RECHECK_RULES,
  SUM_TOLERANCE,
  type RecheckRule,
} from "@/features/invoice-detail/recheck-rules";
import { IBAN_ZEICHEN } from "@/features/invoice-detail/nachpruefung";
import {
  REVIEW_CHECK_GRUND,
  SEVERITY_INFORMATIONAL,
  VALIDIERUNG_FELD_GRUND,
  VALIDIERUNG_GATES,
  VALIDIERUNG_MODIFIER,
} from "@/features/invoice-detail/pruefung";

const quoteList = (values: string[]) => values.map((value) => `'${value}'`).join(",");

const detailAllowlist = quoteList(Object.keys(VALIDIERUNG_FELD_GRUND));
const checkAllowlist = quoteList(["iban_anzahl", ...Object.keys(REVIEW_CHECK_GRUND)]);
const modifierList = quoteList([...VALIDIERUNG_MODIFIER]);
const gateList = quoteList(VALIDIERUNG_GATES as string[]);
const relaxedGates = quoteList(["rechnungsnr_vorhanden", "datum_vorhanden"]);
const ibanSplitPattern = `(?i)(${IBAN_SEPARATOR_PATTERN}|\\y(?:${IBAN_JOINING_WORDS.join("|")})\\y)`;
const ibanShape = IBAN_ZEICHEN.source;

function gated(rule: RecheckRule, body: string): string {
  if (!rule.gatedOnPipeline) return body;
  return `case when lower(btrim(coalesce(halves.basis -> '${rule.field}' ->> 'status', ''))) = 'not_applicable'
          then 'not_applicable'
          else ${body} end`;
}

function ruleSql(rule: RecheckRule): string {
  const body = (() => {
    switch (rule.kind) {
      case "gross_present":
        return `case when p_amount_gross is not null then 'ok' else 'failed' end`;
      case "text_present": {
        const param = {
          issuer: "p_issuer",
          invoice_number: "p_invoice_number",
          recipient_name: "p_recipient_name",
        }[rule.column!];
        return `case when btrim(coalesce(${param}, '')) <> '' then 'ok' else 'failed' end`;
      }
      case "date_present":
        return `case when p_document_date is not null then 'ok' else 'failed' end`;
      case "date_not_future":
        return `case when p_document_date is null then 'not_applicable'
          when p_document_date <= current_date then 'ok' else 'failed' end`;
      case "sum_matches":
        return `case when numbers.subtotal is null or p_amount_net is null or p_vat_amount is null
          then 'not_applicable'
          when abs((p_amount_net::float8 + p_vat_amount::float8) - numbers.subtotal::float8) <= ${SUM_TOLERANCE} then 'ok'
          else 'failed' end`;
      case "vat_rate_valid":
        return `case when p_vat_rate is null or active_rates.rates is null then 'not_applicable'
          when floor(p_vat_rate + 0.5) = any(active_rates.rates) then 'ok' else 'failed' end`;
      case "iban_checksum":
        return `case when cardinality(iban_candidates.arr) = 0 then 'not_applicable'
          when (select bool_and(public.invoice_iban_checksum_ok(c)) from unnest(iban_candidates.arr) c)
            then 'ok' else 'failed' end`;
      case "iban_present":
        return `case when cardinality(iban_candidates.arr) > 0 then 'ok' else 'failed' end`;
      case "iban_unambiguous":
        return `case when cardinality(iban_candidates.arr) = 0 then 'not_applicable'
          when cardinality(iban_candidates.arr) <= 1 then 'ok' else 'failed' end`;
      case "assignment_resolved":
        return `case when btrim(coalesce(p_company_code, '')) <> '' then 'ok' else 'failed' end`;
    }
  })();
  return `      '${rule.field}', ${gated(rule, body)}`;
}

const recheckEntries = RECHECK_RULES.map(ruleSql).join(",\n");

const sql = `-- GENERATED by scripts/generate-review-recheck-sql.ts from
-- src/features/invoice-detail/recheck-rules.ts and pruefung.ts. Do not edit by hand:
-- change the rules and regenerate, so the badge and this function cannot drift apart.

create or replace function public.invoice_iban_checksum_ok(candidate text)
returns boolean
language sql
immutable
set search_path to 'public'
as $fn$
  with cleaned as (
    select upper(regexp_replace(btrim(coalesce(candidate, '')), '\\s', '', 'g')) as s
  ),
  rearranged as (
    select substr(s, 5) || substr(s, 1, 4) as r, s from cleaned
  ),
  expanded as (
    select string_agg(
      case when ch ~ '[0-9]' then ch else (ascii(ch) - 55)::text end, '' order by ord
    ) as digits
    from rearranged, regexp_split_to_table(r, '') with ordinality as t(ch, ord)
  )
  select case
    when (select s from cleaned) !~ '${ibanShape}' then false
    when (select s from cleaned) !~ '^[A-Z]{2}[0-9]{2}' then false
    else (select digits from expanded)::numeric % 97 = 1
  end;
$fn$;

create or replace function public.invoice_review_state(
  p_validation_detail jsonb,
  p_extracted jsonb,
  p_validation jsonb,
  p_issuer text,
  p_invoice_number text,
  p_document_date date,
  p_amount_gross numeric,
  p_amount_net numeric,
  p_vat_amount numeric,
  p_vat_rate numeric,
  p_recipient_name text,
  p_company_code text,
  p_supplier_iban text
)
returns table(problem_count integer, unchecked boolean)
language sql
stable
set search_path to 'public'
as $fn$
  with raw_detail as (
    select coalesce(
      case when jsonb_typeof(p_validation_detail) = 'object' and p_validation_detail <> '{}'::jsonb
        then p_validation_detail end,
      case when jsonb_typeof(p_extracted -> 'validation_detail') = 'object'
            and (p_extracted -> 'validation_detail') <> '{}'::jsonb
        then p_extracted -> 'validation_detail' end,
      '{}'::jsonb
    ) as d
  ),
  halves as (
    select
      case
        when d ? 'bookkeeping_edits' then
          case when jsonb_typeof(d -> 'bookkeeping_edits') = 'object'
                and (d -> 'bookkeeping_edits') <> '{}'::jsonb
            then d -> 'bookkeeping_edits' else '{}'::jsonb end
        else d
      end as basis,
      case
        when d ? 'bookkeeping_edits' and jsonb_typeof(d -> 'user_edits') = 'object'
          then coalesce(d -> 'user_edits', '{}'::jsonb)
        else '{}'::jsonb
      end as stored_user
    from raw_detail
  ),
  iban_input as (
    select coalesce(
      nullif(btrim(coalesce(p_supplier_iban, '')), ''),
      case when jsonb_typeof(p_extracted -> 'iban') = 'string' then p_extracted ->> 'iban' end
    ) as src
  ),
  iban_candidates as (
    select coalesce(array_agg(part) filter (where part <> ''), '{}'::text[]) as arr
    from iban_input,
      lateral (
        select btrim(piece) as part
        from regexp_split_to_table(coalesce(src, ''), '${ibanSplitPattern}') as piece
      ) parts
    where src is not null
  ),
  numbers as (
    select
      coalesce(
        case
          when jsonb_typeof(p_extracted -> 'zwischensumme_brutto') = 'number'
            then (p_extracted ->> 'zwischensumme_brutto')::numeric
          when jsonb_typeof(p_extracted -> 'zwischensumme_brutto') = 'string'
                and (p_extracted ->> 'zwischensumme_brutto') ~ '^\\s*[+-]?([0-9]+\\.?[0-9]*|\\.[0-9]+)([eE][+-]?[0-9]+)?\\s*$'
            then btrim(p_extracted ->> 'zwischensumme_brutto')::numeric
        end,
        p_amount_gross
      ) as subtotal
  ),
  active_rates as (
    select array_agg(rate) as rates
    from halves,
      lateral (
        select case
          when jsonb_typeof(elem) = 'number' then (elem #>> '{}')::numeric
          when jsonb_typeof(elem) = 'string' and (elem #>> '{}') ~ '^\\s*[+-]?([0-9]+\\.?[0-9]*|\\.[0-9]+)([eE][+-]?[0-9]+)?\\s*$'
            then btrim(elem #>> '{}')::numeric
        end as rate
        from jsonb_array_elements(
          case when jsonb_typeof(basis -> 'vat_rate_valid' -> 'values' -> 'active_rates') = 'array'
            then basis -> 'vat_rate_valid' -> 'values' -> 'active_rates'
            else '[]'::jsonb end
        ) as elem
      ) parsed
    where parsed.rate is not null
  ),
  recheck as (
    select jsonb_build_object(
${recheckEntries}
    ) as m
    from halves, iban_candidates, numbers, active_rates
  ),
  final_detail as (
    select case
      when halves.basis <> '{}'::jsonb then coalesce(
        (
          select jsonb_object_agg(
            entry.check_key,
            case when recheck.m ? entry.check_key and jsonb_typeof(entry.check_value) = 'object'
              then jsonb_set(entry.check_value, '{status}', recheck.m -> entry.check_key)
              else entry.check_value end
          )
          from jsonb_each(halves.basis) as entry(check_key, check_value)
        ), '{}'::jsonb)
      else halves.stored_user
    end as detail
    from halves, recheck
  ),
  checks_tier as (
    select case
      when jsonb_typeof(p_extracted -> 'review_checks') = 'array'
            and jsonb_array_length(p_extracted -> 'review_checks') > 0
        then p_extracted -> 'review_checks' end as arr
  ),
  flat_tier as (
    select coalesce(
      case when jsonb_typeof(p_extracted -> 'validation') = 'object'
        then p_extracted -> 'validation' end,
      p_validation, '{}'::jsonb) as fv
  )
  select
    (case
      when final_detail.detail <> '{}'::jsonb then (
        select count(*)::int from jsonb_each(final_detail.detail) as entry(check_key, check_value)
        where entry.check_key in (${detailAllowlist})
          and btrim(lower(coalesce(entry.check_value ->> 'status', ''))) not in ('', 'ok', 'not_applicable', 'skipped')
      )
      when checks_tier.arr is not null then (
        select count(*)::int from jsonb_array_elements(checks_tier.arr) as review_check(value)
        where btrim(lower(coalesce(review_check.value ->> 'severity', ''))) <> '${SEVERITY_INFORMATIONAL}'
          and coalesce(review_check.value ->> 'field', '') in (${checkAllowlist})
          and btrim(lower(coalesce(review_check.value ->> 'status', ''))) not in ('', 'ok', 'not_applicable', 'skipped')
      )
      else (
        select count(*)::int from jsonb_each_text(flat_tier.fv) as gate(gate_name, gate_value)
        where gate.gate_name in (${gateList})
          and gate.gate_value = 'false'
          and (gate.gate_name not in (${relaxedGates})
               or coalesce(flat_tier.fv ->> 'kleinbetrag', '') <> 'true')
      )
    end) as problem_count,
    (case
      when final_detail.detail <> '{}'::jsonb then
        not exists (
          select 1 from jsonb_each(final_detail.detail) as entry(check_key, check_value)
          where entry.check_key not in (${modifierList})
            and btrim(lower(coalesce(entry.check_value ->> 'status', ''))) not in ('', 'not_applicable', 'skipped')
        )
      when checks_tier.arr is not null then
        not exists (
          select 1 from jsonb_array_elements(checks_tier.arr) as review_check(value)
          where btrim(lower(coalesce(review_check.value ->> 'severity', ''))) <> '${SEVERITY_INFORMATIONAL}'
            and btrim(lower(coalesce(review_check.value ->> 'status', ''))) not in ('', 'not_applicable', 'skipped')
        )
      else
        not exists (
          select 1 from jsonb_each_text(flat_tier.fv) as gate(gate_name, gate_value)
          where gate.gate_name in (${gateList})
            and (gate.gate_value = 'true'
                 or (gate.gate_value = 'false'
                     and (gate.gate_name not in (${relaxedGates})
                          or coalesce(flat_tier.fv ->> 'kleinbetrag', '') <> 'true')))
        )
    end) as unchecked
  from final_detail, checks_tier, flat_tier;
$fn$;

revoke execute on function public.invoice_iban_checksum_ok(text) from public, anon;
grant execute on function public.invoice_iban_checksum_ok(text) to authenticated, service_role;
revoke execute on function public.invoice_review_state(jsonb, jsonb, jsonb, text, text, date, numeric, numeric, numeric, numeric, text, text, text) from public, anon;
grant execute on function public.invoice_review_state(jsonb, jsonb, jsonb, text, text, date, numeric, numeric, numeric, numeric, text, text, text) to authenticated, service_role;
`;

const target = process.argv[2];
if (!target) {
  process.stdout.write(sql);
} else {
  writeFileSync(target, sql);
  console.log("written:", target);
}
