-- 20260827170000_invoices_urgency_columns.sql
-- MIRRORED FROM THE EXTRACTION SERVICE, NOT AUTHORED HERE.
--
-- Source of truth: book-keepping/migrations/tenant/0008_urgency_columns.sql, which is what
-- actually ran against the live projects. This copy exists so supabase/migrations/ tells the whole
-- truth about the invoices table: without it, a future session reading only this repo would see
-- 20260827180000 republish v_open_items for five columns that no migration here ever added, and
-- conclude the schema snapshot was wrong.
--
-- Do NOT edit this file to change the schema. Change it in book-keepping and re-copy, or the two
-- will drift and the next tenant rollout will apply a different shape than this repo describes.
--
-- Applied 27.08.2026 to all five tenants (dev-tenant, eiffler, immonetz, mayestate, staeyhub).
-- v_open_items still had to be republished afterwards (see 20260827180000): `select i.*` freezes
-- its column list at creation, so a view never picks up columns added to its table later.

-- Add payment deadline urgency tracking and early-payment discount fields to invoices.
-- Enables prioritization by due date and displays multiple payment deadlines (normal + discount).
-- All column names use English for multi-tenant compatibility.

DO $$
DECLARE
  table_exists BOOLEAN;
BEGIN
  SELECT EXISTS(
    SELECT 1 FROM information_schema.tables
    WHERE table_name = 'invoices' AND table_schema = 'public'
  ) INTO table_exists;

  IF NOT table_exists THEN
    RAISE NOTICE 'invoices table not found, skipping urgency columns migration';
    RETURN;
  END IF;

  BEGIN
    ALTER TABLE invoices ADD COLUMN urgency TEXT;
  EXCEPTION WHEN duplicate_column THEN NULL;
  END;

  BEGIN
    ALTER TABLE invoices ADD COLUMN days_until_due INT;
  EXCEPTION WHEN duplicate_column THEN NULL;
  END;

  BEGIN
    ALTER TABLE invoices ADD COLUMN early_payment_deadline DATE;
  EXCEPTION WHEN duplicate_column THEN NULL;
  END;

  BEGIN
    ALTER TABLE invoices ADD COLUMN early_payment_discount_percent FLOAT;
  EXCEPTION WHEN duplicate_column THEN NULL;
  END;

  BEGIN
    ALTER TABLE invoices ADD COLUMN early_payment_discount_amount FLOAT;
  EXCEPTION WHEN duplicate_column THEN NULL;
  END;

  BEGIN
    ALTER TABLE invoices DROP COLUMN skonto_frist;
  EXCEPTION WHEN undefined_column THEN NULL;
  END;

  BEGIN
    ALTER TABLE invoices DROP COLUMN skonto_prozent;
  EXCEPTION WHEN undefined_column THEN NULL;
  END;

  BEGIN
    ALTER TABLE invoices DROP COLUMN skonto_betrag;
  EXCEPTION WHEN undefined_column THEN NULL;
  END;
END
$$;

COMMENT ON COLUMN invoices.urgency IS 'Payment deadline urgency: overdue|today|within_3_days|within_week|later|not_applicable';
COMMENT ON COLUMN invoices.days_until_due IS 'Days until due_date; negative if overdue (e.g., -5 means 5 days late)';
COMMENT ON COLUMN invoices.early_payment_deadline IS 'Deadline to claim discount (e.g., day 10 in 2/10 Net 30 terms)';
COMMENT ON COLUMN invoices.early_payment_discount_percent IS 'Discount percentage (e.g., 2 for 2% off)';
COMMENT ON COLUMN invoices.early_payment_discount_amount IS 'Discount amount in document currency if paid by deadline';

-- Backfill from extracted JSONB (fills immediately, no reprocess needed)
DO $$
BEGIN
  UPDATE invoices
  SET
    early_payment_deadline = (extracted->>'skonto_frist')::date,
    early_payment_discount_percent = (extracted->>'skonto_prozent')::float,
    early_payment_discount_amount = (extracted->>'skonto_betrag')::float
  WHERE
    (extracted->>'skonto_frist' IS NOT NULL OR
     extracted->>'skonto_prozent' IS NOT NULL OR
     extracted->>'skonto_betrag' IS NOT NULL)
    AND deleted_at IS NULL;

  RAISE NOTICE 'Backfilled skonto fields from extracted JSONB';
END
$$;
